name: .NET
on: [ push, pull_request ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, windows-2025-vs2026 ]
        directory: [ ./cs/DecpyptFile, ./cs/EncpyptFile ./cs/ClearConsole ]
    
    # HIER DIE DEFAULT-EINSTELLUNG SETZEN:
    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      # Der "Change Directory"-Schritt wurde gelöscht, da jetzt alle Schritte hier starten
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
